### ISSUE TITLE
not recommended circuit question

### ISSUE THREAD

**Issue by profknivre** [loehnertj/bsbgateway#17]
In the circuit description it is written that it is not recommended because of lack of galvanic isolation. 

I wonder if it is safe to use with galvanic isolated rs232 to usb adapter?

**Comment by loehnertj** [comment]
**IF** your adapter is really completely isolated, the circuit is safe to use.
I.e. not only the signal wires but also at least DTR and RTS lines, and possibly all the other pins.

OTOH this could mean that it does not work at all, since these two pins are used to power the adapter. If they are decoupled, it could be that you can only draw very little currents out of them. Depends on your actual adapter.

**Comment by profknivre** [comment]
thanks
